export const BASE_URL = "https://spearfisher.app";
export const SITE_NAME = "SpearFisher";
export const SITE_DESCRIPTION =
  "AI-powered cold email personalization. Paste prospect info, get personalized emails that get replies. Built for SDRs, BDRs, and sales teams.";

export const ROLES = [
  "sdr",
  "bdr",
  "account-executive",
  "sales-manager",
  "vp-sales",
  "head-of-growth",
  "founder",
  "ceo",
  "recruiter",
  "talent-acquisition",
  "agency-owner",
  "marketing-director",
  "partnerships-manager",
  "business-development",
  "customer-success",
  "fundraising",
  "investor-relations",
  "pr-outreach",
  "link-building",
  "influencer-outreach",
] as const;

export const INDUSTRIES = [
  "saas",
  "fintech",
  "healthtech",
  "edtech",
  "cybersecurity",
  "ai-ml",
  "ecommerce",
  "real-estate",
  "insurance",
  "legal-services",
  "accounting",
  "manufacturing",
  "logistics",
  "construction",
  "hospitality",
  "media",
  "advertising",
  "consulting",
  "staffing",
  "energy",
  "nonprofit",
  "government",
] as const;

export const USE_CASES = [
  "prospecting",
  "meeting-booking",
  "follow-up",
  "breakup-email",
  "referral-request",
  "partnership-outreach",
  "investor-outreach",
  "recruiting",
  "link-building-outreach",
  "podcast-guest-pitch",
  "event-invitation",
  "product-launch",
  "case-study-request",
  "review-request",
  "upsell-cross-sell",
  "renewal-outreach",
  "win-back",
  "conference-networking",
  "warm-introduction",
  "cold-linkedin-to-email",
] as const;

export const PERSONAS = [
  "cto",
  "cfo",
  "cmo",
  "ciso",
  "vp-engineering",
  "head-of-product",
  "head-of-hr",
  "procurement-manager",
  "it-director",
  "operations-manager",
  "marketing-manager",
  "sales-director",
  "general-counsel",
  "chief-of-staff",
  "board-member",
] as const;

export const CROSS_COMBINATIONS = [
  ["sdr", "saas"],
  ["sdr", "fintech"],
  ["sdr", "cybersecurity"],
  ["sdr", "ai-ml"],
  ["sdr", "healthtech"],
  ["bdr", "saas"],
  ["bdr", "fintech"],
  ["bdr", "ecommerce"],
  ["account-executive", "saas"],
  ["account-executive", "fintech"],
  ["account-executive", "cybersecurity"],
  ["account-executive", "consulting"],
  ["sales-manager", "saas"],
  ["sales-manager", "fintech"],
  ["vp-sales", "saas"],
  ["vp-sales", "fintech"],
  ["head-of-growth", "saas"],
  ["head-of-growth", "ecommerce"],
  ["head-of-growth", "fintech"],
  ["founder", "saas"],
  ["founder", "fintech"],
  ["founder", "ecommerce"],
  ["founder", "ai-ml"],
  ["founder", "healthtech"],
  ["ceo", "saas"],
  ["ceo", "fintech"],
  ["recruiter", "saas"],
  ["recruiter", "fintech"],
  ["recruiter", "staffing"],
  ["recruiter", "consulting"],
  ["recruiter", "cybersecurity"],
  ["talent-acquisition", "saas"],
  ["talent-acquisition", "fintech"],
  ["agency-owner", "saas"],
  ["agency-owner", "advertising"],
  ["agency-owner", "consulting"],
  ["marketing-director", "saas"],
  ["marketing-director", "ecommerce"],
  ["marketing-director", "fintech"],
  ["partnerships-manager", "saas"],
  ["partnerships-manager", "fintech"],
  ["business-development", "saas"],
  ["business-development", "consulting"],
  ["business-development", "fintech"],
  ["customer-success", "saas"],
  ["customer-success", "fintech"],
  ["fundraising", "saas"],
  ["fundraising", "fintech"],
  ["fundraising", "healthtech"],
  ["investor-relations", "saas"],
  ["investor-relations", "fintech"],
  ["pr-outreach", "saas"],
  ["pr-outreach", "media"],
  ["pr-outreach", "fintech"],
  ["link-building", "saas"],
  ["link-building", "ecommerce"],
  ["influencer-outreach", "ecommerce"],
  ["influencer-outreach", "saas"],
  ["sdr", "edtech"],
  ["sdr", "ecommerce"],
  ["sdr", "consulting"],
  ["sdr", "manufacturing"],
  ["sdr", "logistics"],
  ["sdr", "insurance"],
  ["sdr", "legal-services"],
  ["bdr", "cybersecurity"],
  ["bdr", "healthtech"],
  ["bdr", "ai-ml"],
  ["bdr", "edtech"],
  ["bdr", "consulting"],
  ["bdr", "staffing"],
  ["account-executive", "ecommerce"],
  ["account-executive", "healthtech"],
  ["account-executive", "ai-ml"],
  ["account-executive", "insurance"],
  ["account-executive", "manufacturing"],
  ["account-executive", "legal-services"],
  ["sales-manager", "cybersecurity"],
  ["sales-manager", "ecommerce"],
  ["sales-manager", "ai-ml"],
  ["sales-manager", "consulting"],
  ["sales-manager", "healthtech"],
  ["vp-sales", "cybersecurity"],
  ["vp-sales", "ecommerce"],
  ["vp-sales", "ai-ml"],
  ["vp-sales", "consulting"],
  ["head-of-growth", "ai-ml"],
  ["head-of-growth", "edtech"],
  ["head-of-growth", "healthtech"],
  ["head-of-growth", "cybersecurity"],
  ["founder", "edtech"],
  ["founder", "cybersecurity"],
  ["founder", "consulting"],
  ["founder", "real-estate"],
  ["ceo", "ecommerce"],
  ["ceo", "ai-ml"],
  ["ceo", "cybersecurity"],
  ["ceo", "consulting"],
  ["recruiter", "ai-ml"],
  ["recruiter", "healthtech"],
  ["recruiter", "ecommerce"],
  ["recruiter", "manufacturing"],
  ["talent-acquisition", "cybersecurity"],
  ["talent-acquisition", "ai-ml"],
  ["talent-acquisition", "healthtech"],
  ["agency-owner", "ecommerce"],
  ["agency-owner", "media"],
  ["agency-owner", "real-estate"],
  ["marketing-director", "ai-ml"],
  ["marketing-director", "healthtech"],
  ["marketing-director", "media"],
  ["partnerships-manager", "ecommerce"],
  ["partnerships-manager", "ai-ml"],
  ["business-development", "ecommerce"],
  ["business-development", "cybersecurity"],
  ["business-development", "ai-ml"],
  ["customer-success", "ecommerce"],
  ["customer-success", "ai-ml"],
  ["customer-success", "healthtech"],
  ["fundraising", "ai-ml"],
  ["fundraising", "cybersecurity"],
  ["fundraising", "edtech"],
  ["link-building", "media"],
  ["link-building", "fintech"],
  ["influencer-outreach", "media"],
  ["influencer-outreach", "fintech"],
  ["influencer-outreach", "healthtech"],
  ["pr-outreach", "ai-ml"],
  ["pr-outreach", "healthtech"],
  ["pr-outreach", "ecommerce"],
  ["sdr", "staffing"],
  ["sdr", "advertising"],
  ["sdr", "media"],
  ["sdr", "energy"],
  ["sdr", "real-estate"],
  ["sdr", "hospitality"],
  ["sdr", "construction"],
  ["sdr", "accounting"],
  ["bdr", "advertising"],
  ["bdr", "real-estate"],
  ["bdr", "insurance"],
  ["bdr", "logistics"],
  ["bdr", "manufacturing"],
  ["bdr", "legal-services"],
  ["account-executive", "staffing"],
  ["account-executive", "advertising"],
  ["account-executive", "real-estate"],
  ["account-executive", "energy"],
] as const;

export type Category = "roles" | "industries" | "use-cases" | "personas" | "cross";

export function slugToTitle(slug: string): string {
  const overrides: Record<string, string> = {
    sdr: "SDR",
    bdr: "BDR",
    ceo: "CEO",
    cto: "CTO",
    cfo: "CFO",
    cmo: "CMO",
    ciso: "CISO",
    saas: "SaaS",
    "ai-ml": "AI/ML",
    "vp-sales": "VP of Sales",
    "vp-engineering": "VP of Engineering",
    hr: "HR",
    it: "IT",
    pr: "PR",
  };
  if (overrides[slug]) return overrides[slug];
  return slug
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

export function categoryLabel(category: Category): string {
  const labels: Record<Category, string> = {
    roles: "Role",
    industries: "Industry",
    "use-cases": "Use Case",
    personas: "Target Persona",
    cross: "Role + Industry",
  };
  return labels[category];
}
