import { db } from "./db";
import { users, usage, generations } from "./schema";
import { eq, and, sql } from "drizzle-orm";

/** Plan-based email limits per billing period */
const PLAN_LIMITS: Record<string, number> = {
  free: 5,
  pro: 200,
  team: 999999,
  agency: 999999,
};

function getPlanLimit(plan: string): number {
  return PLAN_LIMITS[plan] ?? PLAN_LIMITS.free;
}

/** Returns the first and last day of the current month as ISO date strings (YYYY-MM-DD) */
function getCurrentPeriod(): { periodStart: string; periodEnd: string } {
  const now = new Date();
  const year = now.getFullYear();
  const month = now.getMonth();
  const periodStart = new Date(year, month, 1).toISOString().split("T")[0];
  const periodEnd = new Date(year, month + 1, 0).toISOString().split("T")[0];
  return { periodStart, periodEnd };
}

/**
 * Finds the current billing period's usage record for the user.
 * If none exists for the current month, creates one.
 */
export async function getOrCreateUsagePeriod(userId: string) {
  const { periodStart, periodEnd } = getCurrentPeriod();

  // Try to find existing usage record for this period
  const existing = await db.query.usage.findFirst({
    where: and(
      eq(usage.userId, userId),
      eq(usage.periodStart, periodStart),
    ),
  });

  if (existing) {
    return existing;
  }

  // Look up user's plan to determine limit
  const user = await db.query.users.findFirst({
    where: eq(users.id, userId),
  });

  const plan = user?.plan ?? "free";
  const emailsLimit = getPlanLimit(plan);

  // Create new usage record for this period
  const [created] = await db
    .insert(usage)
    .values({
      userId,
      periodStart,
      periodEnd,
      emailsGenerated: 0,
      emailsLimit,
    })
    .onConflictDoNothing()
    .returning();

  // If onConflictDoNothing hit a race condition, re-fetch
  if (!created) {
    const refetched = await db.query.usage.findFirst({
      where: and(
        eq(usage.userId, userId),
        eq(usage.periodStart, periodStart),
      ),
    });
    return refetched!;
  }

  return created;
}

/**
 * Checks if the user has remaining email generations this period.
 */
export async function checkUsageLimit(userId: string): Promise<{
  allowed: boolean;
  used: number;
  limit: number;
  plan: string;
}> {
  const user = await db.query.users.findFirst({
    where: eq(users.id, userId),
  });
  const plan = user?.plan ?? "free";

  const period = await getOrCreateUsagePeriod(userId);

  return {
    allowed: period.emailsGenerated < period.emailsLimit,
    used: period.emailsGenerated,
    limit: period.emailsLimit,
    plan,
  };
}

/**
 * Increments emails_generated by 1 for the current period and
 * inserts a record into the generations table.
 */
export async function incrementUsage(
  userId: string,
  generationDetails: {
    prospectInfo: string;
    senderContext?: string | null;
    companyUrl?: string | null;
    linkedinUrl?: string | null;
    pdfFilename?: string | null;
    emailsJson: unknown;
    model?: string;
    tokensUsed?: number;
  },
) {
  const { periodStart } = getCurrentPeriod();

  // Increment usage counter
  await db
    .update(usage)
    .set({
      emailsGenerated: sql`${usage.emailsGenerated} + 1`,
    })
    .where(
      and(eq(usage.userId, userId), eq(usage.periodStart, periodStart)),
    );

  // Insert generation record
  await db.insert(generations).values({
    userId,
    prospectInfo: generationDetails.prospectInfo,
    senderContext: generationDetails.senderContext ?? null,
    companyUrl: generationDetails.companyUrl ?? null,
    linkedinUrl: generationDetails.linkedinUrl ?? null,
    pdfFilename: generationDetails.pdfFilename ?? null,
    emailsJson: generationDetails.emailsJson,
    model: generationDetails.model ?? "claude-sonnet-4-6",
    tokensUsed: generationDetails.tokensUsed ?? null,
  });
}

/**
 * Returns usage stats for display in the UI.
 */
export async function getUsageStats(userId: string): Promise<{
  used: number;
  limit: number;
  plan: string;
  resetsAt: Date;
}> {
  const user = await db.query.users.findFirst({
    where: eq(users.id, userId),
  });
  const plan = user?.plan ?? "free";

  const period = await getOrCreateUsagePeriod(userId);

  // Reset date is the first day of the next month
  const now = new Date();
  const resetsAt = new Date(now.getFullYear(), now.getMonth() + 1, 1);

  return {
    used: period.emailsGenerated,
    limit: period.emailsLimit,
    plan,
    resetsAt,
  };
}
